### ISSUE TITLE
Which laptop model is this for?

### ISSUE THREAD

**Issue by coderobe** [1and1get2/CP65S#1]
Hi, you're using [AzulPatcher4600](https://github.com/coderobe/AzulPatcher4600), and i'm trying to figure out which laptops my patch works on - because it seems to be quite a niche fix.

**Comment by coderobe** [comment]
Also, note on https://github.com/1and1get2/CP65S/tree/master/Clover/EFI/CLOVER/kexts - you can safely put it in `Other` as well instead of having it in `10.11` and `10.12`, it'll figure out on its own if it should or shouldn't load on a specific version

**Comment by hereisderek** [comment]
Oh hey! you are the author!
CP65S is a board model that was produced by Clevo, it actually came with many names, such as Sager NP8650 / P650SA, and has been used by various brands, among others, mine in particular, is hasee (Z7M-i78172D1), a brand that is mostly known in China. 
The reason I put it in the specific version folder unlike the others is that there was this one time I received a kernel panic during the installation of 10.13, and your patch was listed among the message. However, the actual cause was still unknown. I still have no luck trying to boot 10.13 installer. I can't even boot into 10.12 recovery or installer partition without a garbled screen.

**Comment by coderobe** [comment]
Ah, thanks for the info! I've added your device to the list of "tested" laptops  

The KP on 10.13 was probably not related to my kext - i have successfully booted 10.13 with that kext on my laptop, but it's not applying any patches yet - i'm waiting on 10.13 to officially drop before releasing a (possibly unstable) version for the betas.
